import { PublisherContext } from '../index';

export function getTypeScriptTemplates(context: PublisherContext): Record<string, string> {
  const apiUrl = process.env.WEBSMITH_API_URL || process.env.NEXT_PUBLIC_API_URL || '';
  const safeName = context.productName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const pkgName = `@websmith/${safeName}-sdk`;
  const companyName = context.product.company_name || context.productName;
  const supportEmail = context.supportEmail || context.product.support_email || '';
  const offlineDays = context.product.offline_days ?? 0;
  const trialDays = context.trialDays ?? context.product.trial_days ?? 7;
  const maxDevices = context.maxDevices ?? (context.product.hardware_binding ? 1 : 999);
  const primaryColor = context.product.primary_color || '#6366f1';

  return {
    'client.ts': `/**
 * ${context.productName} SDK - License Management Client
 * Generated by Websmith License API Center | ${context.generatedAt}
 * Do not edit directly.
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import os from 'os';
import * as readline from 'readline';

// ---------------------------------------------------------------------------
// Generated configuration (from publisher context)
// ---------------------------------------------------------------------------
const API_URL = '${apiUrl}';
const PRODUCT_NAME = '${context.productName}';
const PRODUCT_ID = '${context.productId}';
const SDK_VERSION = '${context.kitVersion}';
const RUNTIME_TYPE = '${context.runtime}';
const RETRYABLE_STATUSES = new Set([500, 502, 503, 504]);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
export interface LicenseResult {
  success?: boolean;
  status?: string;
  valid?: boolean;
  license?: LicenseData;
  message?: string;
  error?: string;
  license_key?: string;
  expires_at?: string;
  plan?: string;
  days_left?: number;
  days_remaining?: number;
  hardware_id?: string;
  [key: string]: any;
}

export interface LicenseData {
  status: string;
  expires_at?: string;
  valid?: boolean;
  plan?: string;
  days_left?: number;
  days_remaining?: number;
  hardware_id?: string;
  [key: string]: any;
}

export interface Fingerprint {
  fingerprint: string;
  platform: string;
  hostname: string;
  identifiers: Record<string, string>;
}

export interface CacheEntry {
  value: any;
  cached_at: number;
}

export interface LicenseStatusData {
  valid: boolean;
  status: string;
  expires_at?: string;
  days_remaining?: number;
  plan?: string;
  hardware_id?: string;
  message?: string;
}

// ---------------------------------------------------------------------------
// ApiError
// ---------------------------------------------------------------------------
export class ApiError extends Error {
  statusCode: number;
  data: Record<string, any>;

  constructor(statusCode: number, message: string, data?: Record<string, any>) {
    super(\`API Error \${statusCode}: \${message}\`);
    this.name = 'ApiError';
    this.statusCode = statusCode;
    this.data = data || {};
  }
}

// ---------------------------------------------------------------------------
// Config loading
// ---------------------------------------------------------------------------
export function loadConfig(): Record<string, any> {
  const searchPaths = [
    path.join(__dirname, 'config', 'api-config.json'),
    path.join(process.cwd(), 'config', 'api-config.json'),
  ];
  for (const cfgPath of searchPaths) {
    try {
      return JSON.parse(fs.readFileSync(cfgPath, 'utf-8'));
    } catch {
      continue;
    }
  }
  // Fallback: return minimal config
  return {
    api: { url: API_URL, public_key: '', secret: '', version: 'v1', timeout: 30000, retry_count: 3 },
    product: { id: PRODUCT_ID, name: PRODUCT_NAME },
    trial: { enabled: ${!!context.product.trial_enabled}, days: ${trialDays} },
    license: { enabled: true, hardware_binding: ${!!context.product.hardware_binding}, max_devices: ${maxDevices}, offline_days: ${offlineDays} },
    hardware: { fingerprint: { include_cpu: true, include_motherboard: true, include_mac: true, include_os: true, hash_algorithm: 'sha256' } },
    branding: { company_name: '${companyName}', primary_color: '${primaryColor}' },
  };
}

// ---------------------------------------------------------------------------
// Crypto utilities
// ---------------------------------------------------------------------------
export function generateTimestamp(): string {
  return new Date().toISOString().replace('+00:00', 'Z');
}

export function generateNonce(): string {
  return crypto.randomUUID();
}

export function signRequest(
  payload: Record<string, any>,
  secret: string,
  timestamp: string,
  nonce: string,
  method: string = 'POST',
  path: string = '',
  query: string = ''
): string {
  const payloadJson = JSON.stringify(payload);
  const bodyHash = crypto.createHash('sha256').update(payloadJson, 'utf-8').digest('hex');
  const message = \`\${method}\\n\${path}\\n\${query}\\n\${bodyHash}\\n\${timestamp}\\n\${nonce}\`;
  return crypto.createHmac('sha256', secret).update(message, 'utf-8').digest('base64');
}

// ---------------------------------------------------------------------------
// HardwareDetector — CPU → Motherboard → MAC → SHA-256
// ---------------------------------------------------------------------------
export class HardwareDetector {
  private _fingerprint: string | null = null;
  private _identifiers: Record<string, string> = {};

  getFingerprint(): string {
    if (this._fingerprint) return this._fingerprint;
    this._identifiers = this._collectIdentifiers();
    const combined = this._buildCombinedString(this._identifiers);
    this._fingerprint = crypto.createHash('sha256').update(combined, 'utf-8').digest('hex');
    return this._fingerprint;
  }

  getIdentifiers(): Record<string, string> {
    if (!this._fingerprint) this.getFingerprint();
    return { ...this._identifiers };
  }

  private _collectIdentifiers(): Record<string, string> {
    const ids: Record<string, string> = {};

    // CPU
    const cpuLabel = this._getCpuLabel();
    if (cpuLabel) ids['cpu'] = cpuLabel;

    // Motherboard / machine
    const machineId = os.machine();
    if (machineId) ids['machine'] = machineId;

    // Network MACs as fallback
    if (!machineId) {
      const macSha = this._getNetworkHash();
      if (macSha) ids['mac'] = macSha;
    }

    // OS info
    ids['os'] = \`\${os.platform()}-\${os.release()}\`;

    return ids;
  }

  private _getCpuLabel(): string {
    try {
      const cpus = os.cpus();
      if (cpus && cpus.length > 0 && cpus[0].model) {
        return cpus[0].model.trim();
      }
    } catch {
      // fall through
    }
    return '';
  }

  private _getNetworkHash(): string {
    try {
      const networkInterfaces = os.networkInterfaces();
      const macs: string[] = [];
      for (const iface of Object.values(networkInterfaces)) {
        if (!iface) continue;
        for (const addr of iface) {
          if (addr && !addr.internal && addr.mac && addr.mac !== '00:00:00:00:00:00') {
            macs.push(addr.mac);
          }
        }
      }
      if (macs.length > 0) {
        const combined = macs.sort().join('|');
        return crypto.createHash('sha256').update(combined, 'utf-8').digest('hex').slice(0, 16);
      }
    } catch {
      // fall through
    }
    return '';
  }

  private _buildCombinedString(identifiers: Record<string, string>): string {
    const parts: string[] = [];
    for (const key of ['cpu', 'machine', 'mac'] as const) {
      if (identifiers[key]) parts.push(identifiers[key]);
    }
    if (identifiers['os']) parts.push(identifiers['os']);
    return parts.join('|');
  }
}

// ---------------------------------------------------------------------------
// CacheManager — TTL-aware, atomic writes
// ---------------------------------------------------------------------------
export class CacheManager {
  private _cacheDir: string;
  private _cacheFile: string;
  private _tmpFile: string;
  private _corruptFile: string;
  private _ttlDays: number;
  private _cache: Record<string, any> | null = null;

  constructor(config: Record<string, any>, productId?: string) {
    const pid = productId || config?.product?.id || PRODUCT_ID;
    const safeName = pid.replace(/[^a-zA-Z0-9_-]/g, '_');
    const homeDir = process.env.WEBSMITH_TEMP_DIR || process.env.TMPDIR || process.env.TEMP || os.homedir();
    this._cacheDir = path.join(homeDir, '.websmith', safeName);
    this._cacheFile = path.join(this._cacheDir, 'cache.json');
    this._tmpFile = path.join(this._cacheDir, 'cache.tmp');
    this._corruptFile = path.join(this._cacheDir, 'cache.corrupt');
    this._ttlDays = config?.offline?.cache_days || config?.license?.offline_days || ${offlineDays};
  }

  private _ensureCacheDir(): void {
    fs.mkdirSync(this._cacheDir, { recursive: true });
  }

  private _loadCache(): Record<string, any> {
    if (this._cache !== null) return this._cache;
    this._ensureCacheDir();
    try {
      if (fs.existsSync(this._cacheFile)) {
        this._cache = JSON.parse(fs.readFileSync(this._cacheFile, 'utf-8'));
        return this._cache!;
      }
    } catch {
      this._preserveCorruptCache();
    }
    this._cache = {};
    return this._cache;
  }

  private _preserveCorruptCache(): void {
    try {
      if (fs.existsSync(this._cacheFile)) {
        if (fs.existsSync(this._corruptFile)) fs.unlinkSync(this._corruptFile);
        fs.renameSync(this._cacheFile, this._corruptFile);
      }
    } catch {
      try { fs.unlinkSync(this._cacheFile); } catch { /* ignore */ }
    }
  }

  private _saveCache(): void {
    if (this._cache === null) return;
    this._ensureCacheDir();
    try {
      fs.writeFileSync(this._tmpFile, JSON.stringify(this._cache, null, 2), 'utf-8');
      fs.renameSync(this._tmpFile, this._cacheFile);
    } catch {
      try { if (fs.existsSync(this._tmpFile)) fs.unlinkSync(this._tmpFile); } catch { /* ignore */ }
    }
  }

  get(key: string): any {
    const cache = this._loadCache();
    const entry = cache[key] as CacheEntry | undefined;
    if (!entry) return null;
    if (this._isExpired(entry)) {
      this.delete(key);
      return null;
    }
    return entry.value;
  }

  set(key: string, value: any): void {
    const cache = this._loadCache();
    cache[key] = { value, cached_at: Date.now() };
    this._saveCache();
  }

  delete(key: string): void {
    const cache = this._loadCache();
    if (key in cache) {
      delete cache[key];
      this._saveCache();
    }
  }

  clear(): void {
    this._cache = {};
    this._saveCache();
  }

  private _isExpired(entry: CacheEntry): boolean {
    const ttlMs = this._ttlDays * 24 * 60 * 60 * 1000;
    return (Date.now() - entry.cached_at) > ttlMs;
  }

  exists(): boolean {
    return fs.existsSync(this._cacheFile);
  }

  isCacheValid(): boolean {
    const cache = this._loadCache();
    const entry = cache['license_status'] as CacheEntry | undefined;
    if (!entry) return false;
    return !this._isExpired(entry);
  }

  getLicenseStatus(): Record<string, any> | null {
    return this.get('license_status');
  }

  setLicenseStatus(status: Record<string, any>): void {
    this.set('license_status', status);
  }

  invalidateLicenseStatus(): void {
    this.delete('license_status');
  }

  setOnboardingComplete(): void {
    const cache = this._loadCache();
    cache['onboarding_complete'] = { value: true, cached_at: Date.now() };
    this._saveCache();
  }

  isOnboardingComplete(): boolean {
    return this.get('onboarding_complete') === true;
  }
}

// ---------------------------------------------------------------------------
// ApiClient — HMAC-signed requests with retry
// ---------------------------------------------------------------------------
export class ApiClient {
  private config: Record<string, any>;
  private apiConfig: Record<string, any>;
  private baseUrl: string;
  private apiVersion: string;
  private apiKey: string;
  private apiSecret: string;
  private timeout: number;
  private retryCount: number;
  private productId: string;
  private hardware: HardwareDetector;
  private cache: CacheManager | null;

  constructor(
    config: Record<string, any>,
    hardware?: HardwareDetector,
    cache?: CacheManager | null
  ) {
    this.config = config;
    this.apiConfig = config.api || {};
    this.baseUrl = (this.apiConfig.url || API_URL).replace(/\\/+$/, '');
    this.apiVersion = this.apiConfig.version || 'v1';
    this.apiKey = this.apiConfig.public_key || '';
    this.apiSecret = this.apiConfig.secret || '';
    this.timeout = (this.apiConfig.timeout || 30000) / 1000;
    this.retryCount = this.apiConfig.retry_count || 3;
    this.productId = config.product?.id || PRODUCT_ID;
    this.hardware = hardware || new HardwareDetector();
    this.cache = cache || null;
  }

  private _getHardwareId(): string {
    return this.hardware.getFingerprint();
  }

  private _buildSignedHeaders(
    payload: Record<string, any>,
    method: string = 'POST',
    path: string = '',
    query: string = ''
  ): Record<string, string> {
    const timestamp = generateTimestamp();
    const nonce = generateNonce();
    const signature = signRequest(payload, this.apiSecret, timestamp, nonce, method, path, query);
    return {
      'Content-Type': 'application/json',
      'x-api-key': this.apiKey,
      'x-timestamp': timestamp,
      'x-nonce': nonce,
      'x-signature': signature,
    };
  }

  private async _request(
    endpoint: string,
    payload: Record<string, any>,
    retries?: number
  ): Promise<Record<string, any>> {
    const url = \`\${this.baseUrl}/api/\${this.apiVersion}/\${endpoint}\`;
    const maxRetries = retries ?? this.retryCount;
    const requestPayload = { ...payload };
    if (this.productId) {
      requestPayload.product_id = requestPayload.product_id || this.productId;
    }

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      const apiPath = \`/api/\${this.apiVersion}/\${endpoint}\`;
      const headers = this._buildSignedHeaders(requestPayload, 'POST', apiPath, '');

      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), this.timeout * 1000);

        const response = await fetch(url, {
          method: 'POST',
          headers,
          body: JSON.stringify(requestPayload),
          signal: controller.signal,
        });
        clearTimeout(timeoutId);

        let data: Record<string, any> = {};
        try {
          data = await response.json();
        } catch {
          const text = await response.text().catch(() => '');
          if (text) data = { message: text };
        }

        if (response.ok) return data;

        if (response.status === 429) {
          if (attempt < maxRetries) {
            const retryAfter = parseInt(response.headers.get('Retry-After') || '5', 10);
            await new Promise(resolve => setTimeout(resolve, retryAfter * 1000));
            continue;
          }
          throw new ApiError(429, 'Rate limit exceeded', data);
        }

        if (RETRYABLE_STATUSES.has(response.status)) {
          if (attempt < maxRetries) {
            await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 2000));
            continue;
          }
          throw new ApiError(response.status, 'Server error', data);
        }

        const message = data.message || data.error || \`HTTP \${response.status}\`;
        throw new ApiError(response.status, message, data);
      } catch (err: any) {
        if (err instanceof ApiError) throw err;
        if (err.name === 'AbortError') {
          if (attempt < maxRetries) {
            await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 2000));
            continue;
          }
          throw new ApiError(504, \`Request timeout after \${this.timeout}s\`);
        }
        if (err.type === 'system' || err.code === 'ECONNREFUSED' || err.code === 'ENOTFOUND') {
          if (attempt < maxRetries) {
            await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 2000));
            continue;
          }
          throw new ApiError(503, \`Connection error: \${err.message}\`);
        }
        if (attempt < maxRetries) {
          await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 2000));
          continue;
        }
        throw new ApiError(500, \`Request failed: \${err.message}\`);
      }
    }
    throw new ApiError(500, \`Failed after \${maxRetries} retries\`);
  }

  async validateLicense(licenseKey: string, hardwareId?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const payload = { action: 'validate', license_key: licenseKey, hardware_id: hardwareId };
    if (this.cache && this.cache.isCacheValid()) {
      const cached = this.cache.getLicenseStatus();
      if (cached) return cached;
    }
    const response = await this._request('license', payload);
    if (this.cache && response.valid) {
      this.cache.setLicenseStatus(response);
    }
    return response;
  }

  async activateLicense(licenseKey: string, hardwareId?: string, deviceName?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const payload: Record<string, any> = { action: 'activate', license_key: licenseKey, hardware_id: hardwareId };
    if (deviceName) payload.device_name = deviceName;
    const response = await this._request('license', payload);
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }

  async deactivateLicense(licenseKey: string, hardwareId?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const response = await this._request('license', { action: 'deactivate', license_key: licenseKey, hardware_id: hardwareId });
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }

  async renewLicense(licenseKey: string, extraDays?: number): Promise<Record<string, any>> {
    const payload: Record<string, any> = { action: 'renew', license_key: licenseKey };
    if (extraDays !== undefined) payload.extra_days = extraDays;
    const response = await this._request('license', payload);
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }

  async startTrial(email: string, customerName: string = '', customerData?: Record<string, any>): Promise<Record<string, any>> {
    const hardwareId = this._getHardwareId();
    const payload: Record<string, any> = { action: 'start', customer_email: email, customer_name: customerName, hardware_id: hardwareId };
    if (customerData) payload.customer_data = customerData;
    return this._request('trial', payload);
  }

  async getTrialStatus(hardwareId?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    return this._request('trial', { action: 'status', hardware_id: hardwareId });
  }

  async convertTrial(hardwareId?: string, plan?: string, name?: string, email?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const payload: Record<string, any> = { action: 'convert', hardware_id: hardwareId };
    if (plan) payload.plan = plan;
    if (name) payload.customer_name = name;
    if (email) payload.customer_email = email;
    const response = await this._request('trial', payload);
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }

  async bindDevice(licenseKey: string, hardwareId?: string, deviceName?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const payload: Record<string, any> = { action: 'bind', license_key: licenseKey, hardware_id: hardwareId };
    if (deviceName) payload.device_name = deviceName;
    return this._request('device', payload);
  }

  async replaceDevice(licenseKey: string, newHardwareId?: string, oldHardwareId?: string): Promise<Record<string, any>> {
    if (!newHardwareId) newHardwareId = this._getHardwareId();
    if (!oldHardwareId) throw new ApiError(400, 'old_hardware_id is required for device replacement');
    const payload = { action: 'replace', license_key: licenseKey, old_hardware_id: oldHardwareId, new_hardware_id: newHardwareId };
    const response = await this._request('device', payload);
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }
}

// ---------------------------------------------------------------------------
// LicenseEngine — full lifecycle management
// ---------------------------------------------------------------------------
export class LicenseEngine {
  private config: Record<string, any>;
  private hardware: HardwareDetector;
  private cache: CacheManager;
  private client: ApiClient;
  private _status: LicenseStatusData | null = null;
  private _licenseKey: string | null = null;

  constructor(config?: Record<string, any>) {
    this.config = config || loadConfig();
    this.hardware = new HardwareDetector();
    this.cache = new CacheManager(this.config);
    this.client = new ApiClient(this.config, this.hardware, this.cache);
  }

  getClient(): ApiClient { return this.client; }
  getHardware(): HardwareDetector { return this.hardware; }
  getCache(): CacheManager { return this.cache; }
  getStatus(): LicenseStatusData | null { return this._status; }
  getLicenseKey(): string | null { return this._licenseKey; }
  hasLicenseKey(): boolean { return this._licenseKey !== null; }

  async initialize(): Promise<LicenseStatusData> {
    if (this.cache.isCacheValid()) {
      const cached = this.cache.getLicenseStatus();
      if (cached) {
        this._status = LicenseEngine._toStatusData(cached);
        return this._status;
      }
    }
    try {
      const hardwareId = this.hardware.getFingerprint();
      const response = await this.client.validateLicense(hardwareId);
      this._status = LicenseEngine._toStatusData({
        valid: response.valid ?? false,
        status: response.status || 'unlicensed',
        expires_at: response.expires_at,
        days_remaining: response.days_left ?? response.days_remaining ?? 0,
        plan: response.plan,
        hardware_id: hardwareId,
        message: response.message,
      });
      if (this._status.valid) {
        this.cache.setLicenseStatus(this._status);
      }
      return this._status;
    } catch (err: any) {
      const cached = this.cache.getLicenseStatus();
      if (cached) {
        this._status = LicenseEngine._toStatusData(cached);
        return this._status;
      }
      this._status = {
        valid: false,
        status: 'error',
        message: \`Unexpected error: \${err.message || err}\`,
      };
      return this._status;
    }
  }

  async validate(key?: string): Promise<LicenseResult> {
    const hardwareId = this.hardware.getFingerprint();
    try {
      const result = await this.client.validateLicense(key || '', hardwareId);
      this._status = LicenseEngine._toStatusData({
        valid: result.valid ?? false,
        status: result.status || 'unknown',
        expires_at: result.expires_at,
        days_remaining: result.days_left ?? result.days_remaining ?? 0,
        plan: result.plan,
        hardware_id: hardwareId,
      });
      if (result.license_key) this._licenseKey = result.license_key;
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async activate(key: string, deviceName: string): Promise<LicenseResult> {
    try {
      const hardwareId = this.hardware.getFingerprint();
      const result = await this.client.activateLicense(key, hardwareId, deviceName);
      if (result.success || result.valid) {
        this._licenseKey = key;
        await this.initialize();
      }
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async deactivate(key?: string): Promise<LicenseResult> {
    const licenseKey = key || this._licenseKey;
    if (!licenseKey) return { success: false, status: 'error', message: 'License key unavailable. Provide a key.' };
    try {
      const result = await this.client.deactivateLicense(licenseKey);
      if (result.success) {
        this.cache.invalidateLicenseStatus();
        this._status = null;
        if (!key) this._licenseKey = null;
      }
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async renew(key?: string, extraDays?: number): Promise<LicenseResult> {
    const licenseKey = key || this._licenseKey;
    if (!licenseKey) return { success: false, status: 'error', message: 'License key unavailable. Activate first.' };
    try {
      const result = await this.client.renewLicense(licenseKey, extraDays);
      if (result.success) await this.initialize();
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async startTrial(email: string, name?: string): Promise<LicenseResult> {
    try {
      const result = await this.client.startTrial(email, name || '');
      if (result.success) await this.initialize();
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async checkTrial(hardwareId?: string): Promise<LicenseResult> {
    try {
      return await this.client.getTrialStatus(hardwareId);
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async convertTrial(hardwareId: string, plan: string, name: string, email: string): Promise<LicenseResult> {
    try {
      const result = await this.client.convertTrial(hardwareId, plan, name, email);
      if (result.success) {
        if (result.license_key) this._licenseKey = result.license_key;
        await this.initialize();
      }
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async replaceHardware(oldDeviceId: string, newDeviceId: string, key?: string): Promise<LicenseResult> {
    const licenseKey = key || this._licenseKey;
    if (!licenseKey) return { success: false, status: 'error', message: 'License key unavailable.' };
    try {
      const result = await this.client.replaceDevice(licenseKey, newDeviceId, oldDeviceId);
      if (result.success) {
        this.cache.invalidateLicenseStatus();
        this._status = null;
        await this.initialize();
      }
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async bindDevice(licenseKey: string, deviceName?: string): Promise<LicenseResult> {
    try {
      const result = await this.client.bindDevice(licenseKey, undefined, deviceName);
      if (result.success) await this.initialize();
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  isValid(): boolean {
    if (!this._status) return false;
    if (this._status.status !== 'active') return false;
    if (this._status.expires_at) {
      if (new Date(this._status.expires_at) < new Date()) return false;
    }
    return true;
  }

  getLicenseInfo(): LicenseStatusData | null {
    return this._status;
  }

  private static _toStatusData(data: any): LicenseStatusData {
    return {
      valid: !!data.valid,
      status: data.status || 'unknown',
      expires_at: data.expires_at,
      days_remaining: data.days_remaining ?? 0,
      plan: data.plan,
      hardware_id: data.hardware_id,
      message: data.message,
    };
  }
}

// ---------------------------------------------------------------------------
// WelcomeDialog — terminal-based license entry dialog
// ---------------------------------------------------------------------------
export class WelcomeDialog {
  private config: Record<string, any>;
  private client: ApiClient;
  private hardware: HardwareDetector;
  private cache: CacheManager;
  private productName: string;
  private trialEnabled: boolean;
  private branding: Record<string, any>;

  constructor(
    client?: ApiClient,
    config?: Record<string, any>,
    productName?: string
  ) {
    this.config = config || loadConfig();
    this.client = client || new ApiClient(this.config);
    this.hardware = new HardwareDetector();
    this.cache = new CacheManager(this.config);
    this.productName = productName || this.config.product?.name || PRODUCT_NAME;
    this.trialEnabled = this.config.trial?.enabled ?? ${!!context.product.trial_enabled};
    this.branding = this.config.branding || {};
  }

  isOnboardingComplete(): boolean {
    return this.cache.isOnboardingComplete();
  }

  async show(): Promise<Record<string, any>> {
    if (!this.trialEnabled) {
      console.log('Trial onboarding is not enabled for this product.');
      return { skipped: true, message: 'Trial onboarding is not enabled' };
    }
    if (this.isOnboardingComplete()) {
      console.log('Onboarding already completed.');
      return { skipped: true, message: 'Onboarding already completed' };
    }

    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const ask = (query: string): Promise<string> =>
      new Promise(resolve => rl.question(query, resolve));

    try {
      console.log(\`\\n=== Welcome to \${this.productName} ===\\n\`);

      const name = await ask('Full Name *: ');
      if (!name.trim()) throw new Error('Name is required');

      const email = await ask('Email *: ');
      if (!email.trim() || !email.includes('@')) throw new Error('Valid email is required');

      const company = await ask('Company (optional): ');

      console.log(\`\\nStarting trial for \${email}...\`);
      const result = await this.client.startTrial(email, name, {
        company_name: company,
        hardware_id: this.hardware.getFingerprint(),
      });

      if (result.success) {
        this.cache.setOnboardingComplete();
        console.log(\`\\nTrial activated! You can now use \${this.productName}.\\n\`);
        return { name, email, hardware_id: this.hardware.getFingerprint(), onboarding_complete: true };
      }

      throw new Error(result.message || 'Failed to start trial');
    } finally {
      rl.close();
    }
  }
}
`,
    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "declaration": true,
    "outDir": "./dist",
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["*.ts"]
}
`,
    'package.json': `{
  "name": "${pkgName}",
  "version": "${context.kitVersion}",
  "description": "${context.productName} SDK — license management client for ${context.runtime}",
  "main": "dist/client.js",
  "types": "dist/client.d.ts",
  "files": [
    "dist/",
    "config/"
  ],
  "scripts": {
    "build": "tsc",
    "prepublishOnly": "npm run build"
  },
  "license": "MIT",
  "dependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  }
}
`,
    'README.md': `# ${context.productName} SDK (TypeScript)

## Version
${context.kitVersion}

## Installation

\`\`\`bash
npm install ${pkgName}
\`\`\`

Or copy the generated \`client.ts\` into your project directly.

## Quick Start

\`\`\`typescript
import { LicenseEngine } from './client';

async function main() {
  const engine = new LicenseEngine();
  const status = await engine.initialize();
  console.log('License status:', status);
}

main();
\`\`\`

## Lifecycle Guide

### 1. Initialize

Loads config from \`./config/api-config.json\` and checks cached license status.

\`\`\`typescript
const engine = new LicenseEngine();
const status = await engine.initialize();
console.log(status.valid ? 'Licensed' : 'Unlicensed');
\`\`\`

### 2. Validate a License Key

\`\`\`typescript
const result = await engine.validate('XXXX-XXXX-XXXX-XXXX');
console.log('Valid:', engine.isValid());
\`\`\`

### 3. Activate a License

Binds the license to the current hardware fingerprint.

\`\`\`typescript
const result = await engine.activate('XXXX-XXXX-XXXX-XXXX', 'My Machine');
if (result.success) console.log('Activated');
\`\`\`

### 4. Start a Trial

\`\`\`typescript
const result = await engine.startTrial('user@example.com', 'John Doe');
if (result.success) console.log('Trial started');
\`\`\`

### 5. Check Trial Status

\`\`\`typescript
const result = await engine.checkTrial();
console.log('Trial:', result.status);
\`\`\`

### 6. Convert Trial to Full License

\`\`\`typescript
const result = await engine.convertTrial(
  engine.getHardware().getFingerprint(),
  'premium',
  'John Doe',
  'user@example.com'
);
if (result.success) console.log('Converted to full license');
\`\`\`

### 7. Renew a License

\`\`\`typescript
const result = await engine.renew(undefined, 365);
if (result.success) console.log('License renewed');
\`\`\`

### 8. Replace Hardware

Transfer a license from one machine to another.

\`\`\`typescript
const oldDeviceId = engine.getLicenseInfo()?.hardware_id || 'OLD_ID';
const newDeviceId = engine.getHardware().getFingerprint();
const result = await engine.replaceHardware(oldDeviceId, newDeviceId);
\`\`\`

### 9. Bind Device

Associate a license with a specific device name.

\`\`\`typescript
const result = await engine.bindDevice('XXXX-XXXX-XXXX-XXXX', 'Workstation-1');
\`\`\`

### 10. Deactivate

\`\`\`typescript
const result = await engine.deactivate();
if (result.success) console.log('License deactivated');
\`\`\`

### 11. Welcome Dialog (Terminal)

Interactive terminal prompt to start a trial.

\`\`\`typescript
import { WelcomeDialog } from './client';

const dialog = new WelcomeDialog();
if (!dialog.isOnboardingComplete()) {
  const result = await dialog.show();
  console.log('Onboarding result:', result);
}
\`\`\`

## API Endpoints

| Method | Endpoint | Description |
|--------|----------|-------------|
| POST | \`/api/v1/license\` | validate, activate, deactivate, renew |
| POST | \`/api/v1/trial\` | start, status, convert |
| POST | \`/api/v1/device\` | bind, replace |
| POST | \`/api/v1/auth/otp/*\` | send, verify |
| GET | \`/api/v1/countries\` | country list |
| GET | \`/api/v1/status\` | health check |

## Configuration

Place \`config/api-config.json\` in your project root:

\`\`\`json
{
  "api": {
    "url": "${apiUrl}",
    "public_key": "your-api-key",
    "secret": "your-api-secret",
    "version": "v1",
    "timeout": 30000,
    "retry_count": 3
  },
  "product": {
    "id": "${context.productId}",
    "name": "${context.productName}"
  }
}
\`\`\`

## License

Generated by Websmith License API Center
Copyright (c) ${new Date().getFullYear()}
`,

    // ================================================================
    // UNIVERSAL LICENSE CENTER & EMAIL DIALOG
    // ================================================================

    'universal_license_center.ts': `/**
 * ${context.productName} SDK - Universal License Center
 * Generated by Websmith License API Center | ${context.generatedAt}
 * Do not edit directly.
 */
import { LicenseEngine, LicenseStatus, ApiClient, HardwareDetector, CacheManager } from './client';
import { UniversalEmailDialog } from './universal_email_dialog';

const SDK_VERSION = '${context.kitVersion}';
const RUNTIME_TYPE = '${context.runtime}';
const SUPPORT_EMAIL = 'support@websmithdigital.com';

export class UniversalLicenseCenter {
  private engine: LicenseEngine;
  private client: ApiClient;
  private hardware: HardwareDetector;
  private cache: CacheManager;
  private config: Record<string, any>;
  private emailDialog: UniversalEmailDialog;
  private status: any = null;

  constructor(config?: Record<string, any>) {
    this.config = config || {};
    this.hardware = new HardwareDetector();
    this.cache = new CacheManager(this.config);
    this.engine = new LicenseEngine(this.config);
    this.client = new ApiClient(this.config, this.hardware, this.cache);
    this.emailDialog = new UniversalEmailDialog(this.config, this.client, this.hardware, this.cache);
  }

  async initialize(): Promise<any> {
    this.status = await this.engine.initialize();
    return this.status;
  }

  async show(): Promise<Record<string, any>> {
    console.log('=== UNIVERSAL LICENSE CENTER ===');
    console.log(\`SDK Version: \${SDK_VERSION} | Runtime: \${RUNTIME_TYPE}\`);
    await this.initialize();
    return { status: this.status ? this.status.toDict() : null };
  }

  getStatus(): any { return this.status; }
  getLicenseKey(): string | null { return this.engine.getLicenseKey(); }
  getHardwareId(): string { return this.hardware.getFingerprint(); }

  async submitRequest(requestType: string, subject: string, message?: string, autoFill?: Record<string, string>): Promise<Record<string, any>> {
    return this.emailDialog.show({ requestType, subject, message, autoFill });
  }

  async startTrial(name: string, email: string): Promise<Record<string, any>> {
    if (!name.trim() || !email.trim()) return { success: false, message: 'Name and email required.' };
    const result = await this.engine.startTrial(email.trim(), name.trim());
    if (result.success) await this.initialize();
    return result;
  }

  async activateLicense(licenseKey: string): Promise<Record<string, any>> {
    if (!licenseKey.trim()) return { success: false, message: 'License key required.' };
    const result = await this.engine.activate(licenseKey.trim());
    if (result.success) await this.initialize();
    return result;
  }

  async renew(extraDays?: number): Promise<Record<string, any>> {
    const result = await this.engine.renew(extraDays);
    if (result.success) await this.initialize();
    return result;
  }

  async replaceHardware(): Promise<Record<string, any>> {
    const result = await this.engine.replaceHardware();
    if (result.success) await this.initialize();
    return result;
  }

  async deactivate(licenseKey?: string): Promise<Record<string, any>> {
    return this.engine.deactivate(licenseKey);
  }
}
`,
    'universal_email_dialog.ts': `/**
 * ${context.productName} SDK - Universal Email Dialog
 * Generated by Websmith License API Center | ${context.generatedAt}
 * Do not edit directly.
 */
const SDK_VERSION = '${context.kitVersion}';
const RUNTIME_TYPE = '${context.runtime}';

export class UniversalEmailDialog {
  private config: Record<string, any>;
  private client: any;
  private hardware: any;
  private cache: any;

  constructor(config: Record<string, any>, client: any, hardware: any, cache: any) {
    this.config = config;
    this.client = client;
    this.hardware = hardware;
    this.cache = cache;
  }

  async show(options: { requestType: string; subject?: string; message?: string; autoFill?: Record<string, string> }): Promise<Record<string, any>> {
    const productName = this.config.product?.name || '${context.productName}';
    const supportEmail = 'support@websmithdigital.com';
    const name = options.autoFill?.customer_name || '';
    const email = options.autoFill?.customer_email || '';
    const hardwareId = options.autoFill?.hardware_id || this.hardware?.getFingerprint() || '';
    const licenseKey = options.autoFill?.license_key || '';
    const planName = options.autoFill?.plan_name || '';

    const payload = { request_type: options.requestType, customer_name: name || 'SDK User', customer_email: email || 'user@example.com', product_name: productName, plan_name: planName, license_key: licenseKey, hardware_id: hardwareId, sdk_version: SDK_VERSION, runtime_type: RUNTIME_TYPE, subject: options.subject || \`\${options.requestType} Request\`, message: options.message || \`\${options.requestType} request from SDK\` };

    try {
      const baseUrl = this.config.api?.url || '';
      const apiKey = this.config.api?.public_key || '';
      const headers: Record<string, string> = { 'Content-Type': 'application/json' };
      if (apiKey) headers['X-API-Key'] = apiKey;
      const response = await fetch(\`\${baseUrl}/api/v1/request\`, { method: 'POST', headers, body: JSON.stringify(payload) });
      const result = await response.json();
      return result.success ? { sent: true, request_id: result.data?.request_id } : { sent: false, error: result.error?.message || 'Request failed' };
    } catch (e: any) {
      return { sent: false, error: e.message, fallback_email: supportEmail };
    }
  }
}
`,
    'index.ts': `/**
 * ${context.productName} SDK - Universal License Center
 * Generated by Websmith License API Center | ${context.generatedAt}
 * Do not edit directly.
 */
import { LicenseEngine, LicenseStatus, ApiClient, ApiError, HardwareDetector, CacheManager } from './client';
import { UniversalLicenseCenter } from './universal_license_center';
import { UniversalEmailDialog } from './universal_email_dialog';

export { UniversalLicenseCenter, UniversalEmailDialog, LicenseEngine, LicenseStatus, ApiClient, ApiError, HardwareDetector, CacheManager };
`,
  };
}
