import { PublisherContext } from '../index';

export function getTypeScriptTemplates(context: PublisherContext): Record<string, string> {
  const apiUrl = process.env.WEBSMITH_API_URL || process.env.NEXT_PUBLIC_API_URL || '';
  const safeName = context.productName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const pkgName = `@websmith/${safeName}-sdk`;
  const companyName = context.product.company_name || context.productName;
  const supportEmail = context.supportEmail || context.product.support_email || '';
  const offlineDays = context.product.offline_days ?? 0;
  const trialDays = context.trialDays ?? context.product.trial_days ?? 7;
  const maxDevices = context.maxDevices ?? (context.product.hardware_binding ? 1 : 999);
  const primaryColor = context.product.primary_color || '#6366f1';

  return {
    'client.ts': `/**
 * ${context.productName} SDK - License Management Client
 * Generated by Websmith License API Center | ${context.generatedAt}
 * Do not edit directly.
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import os from 'os';
import * as readline from 'readline';

// ---------------------------------------------------------------------------
// Generated configuration (from publisher context)
// ---------------------------------------------------------------------------
const API_URL = '${apiUrl}';
const PRODUCT_NAME = '${context.productName}';
const PRODUCT_ID = '${context.productId}';
const SDK_VERSION = '${context.kitVersion}';
const RUNTIME_TYPE = '${context.runtime}';
const RETRYABLE_STATUSES = new Set([500, 502, 503, 504]);

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
export interface LicenseResult {
  success?: boolean;
  status?: string;
  valid?: boolean;
  license?: LicenseData;
  message?: string;
  error?: string;
  license_key?: string;
  expires_at?: string;
  plan?: string;
  days_left?: number;
  days_remaining?: number;
  hardware_id?: string;
  [key: string]: any;
}

export interface LicenseData {
  status: string;
  expires_at?: string;
  valid?: boolean;
  plan?: string;
  days_left?: number;
  days_remaining?: number;
  hardware_id?: string;
  [key: string]: any;
}

export interface Fingerprint {
  fingerprint: string;
  platform: string;
  hostname: string;
  identifiers: Record<string, string>;
}

export interface CacheEntry {
  value: any;
  cached_at: number;
}

export interface LicenseStatusData {
  valid: boolean;
  status: string;
  expires_at?: string;
  days_remaining?: number;
  plan?: string;
  hardware_id?: string;
  message?: string;
  license_key?: string;
}

// ---------------------------------------------------------------------------
// ApiError
// ---------------------------------------------------------------------------
export class ApiError extends Error {
  statusCode: number;
  data: Record<string, any>;

  constructor(statusCode: number, message: string, data?: Record<string, any>) {
    super(\`API Error \${statusCode}: \${message}\`);
    this.name = 'ApiError';
    this.statusCode = statusCode;
    this.data = data || {};
  }
}

// ---------------------------------------------------------------------------
// Config loading
// ---------------------------------------------------------------------------
export function loadConfig(): Record<string, any> {
  const searchPaths = [
    path.join(__dirname, 'config', 'api-config.json'),
    path.join(process.cwd(), 'config', 'api-config.json'),
  ];
  for (const cfgPath of searchPaths) {
    try {
      return JSON.parse(fs.readFileSync(cfgPath, 'utf-8'));
    } catch {
      continue;
    }
  }
  // Fallback: return minimal config
  return {
    api: { url: API_URL, public_key: '', secret: '', version: 'v1', timeout: 30000, retry_count: 3 },
    product: { id: PRODUCT_ID, name: PRODUCT_NAME },
    trial: { enabled: ${!!context.product.trial_enabled}, days: ${trialDays} },
    license: { enabled: true, hardware_binding: ${!!context.product.hardware_binding}, max_devices: ${maxDevices}, offline_days: ${offlineDays} },
    hardware: { fingerprint: { include_cpu: true, include_motherboard: true, include_mac: true, include_os: true, hash_algorithm: 'sha256' } },
    branding: { company_name: '${companyName}', primary_color: '${primaryColor}' },
  };
}

// ---------------------------------------------------------------------------
// Crypto utilities
// ---------------------------------------------------------------------------
export function generateTimestamp(): string {
  return new Date().toISOString().replace('+00:00', 'Z');
}

export function generateNonce(): string {
  return crypto.randomUUID();
}

export function signRequest(
  payload: Record<string, any>,
  secret: string,
  timestamp: string,
  nonce: string,
  method: string = 'POST',
  path: string = '',
  query: string = ''
): string {
  const payloadJson = JSON.stringify(payload);
  const bodyHash = crypto.createHash('sha256').update(payloadJson, 'utf-8').digest('hex');
  const message = \`\${method}\\n\${path}\\n\${query}\\n\${bodyHash}\\n\${timestamp}\\n\${nonce}\`;
  return crypto.createHmac('sha256', secret).update(message, 'utf-8').digest('base64');
}

// ---------------------------------------------------------------------------
// HardwareDetector — CPU → Motherboard → MAC → SHA-256
// ---------------------------------------------------------------------------
export class HardwareDetector {
  private _fingerprint: string | null = null;
  private _identifiers: Record<string, string> = {};

  getFingerprint(): string {
    if (this._fingerprint) return this._fingerprint;
    this._identifiers = this._collectIdentifiers();
    const combined = this._buildCombinedString(this._identifiers);
    this._fingerprint = crypto.createHash('sha256').update(combined, 'utf-8').digest('hex');
    return this._fingerprint;
  }

  getIdentifiers(): Record<string, string> {
    if (!this._fingerprint) this.getFingerprint();
    return { ...this._identifiers };
  }

  private _collectIdentifiers(): Record<string, string> {
    const ids: Record<string, string> = {};

    // CPU
    const cpuLabel = this._getCpuLabel();
    if (cpuLabel) ids['cpu'] = cpuLabel;

    // Motherboard / machine
    const machineId = os.machine();
    if (machineId) ids['machine'] = machineId;

    // Network MACs as fallback
    if (!machineId) {
      const macSha = this._getNetworkHash();
      if (macSha) ids['mac'] = macSha;
    }

    // OS info
    ids['os'] = \`\${os.platform()}-\${os.release()}\`;

    return ids;
  }

  private _getCpuLabel(): string {
    try {
      const cpus = os.cpus();
      if (cpus && cpus.length > 0 && cpus[0].model) {
        return cpus[0].model.trim();
      }
    } catch {
      // fall through
    }
    return '';
  }

  private _getNetworkHash(): string {
    try {
      const networkInterfaces = os.networkInterfaces();
      const macs: string[] = [];
      for (const iface of Object.values(networkInterfaces)) {
        if (!iface) continue;
        for (const addr of iface) {
          if (addr && !addr.internal && addr.mac && addr.mac !== '00:00:00:00:00:00') {
            macs.push(addr.mac);
          }
        }
      }
      if (macs.length > 0) {
        const combined = macs.sort().join('|');
        return crypto.createHash('sha256').update(combined, 'utf-8').digest('hex').slice(0, 16);
      }
    } catch {
      // fall through
    }
    return '';
  }

  private _buildCombinedString(identifiers: Record<string, string>): string {
    const parts: string[] = [];
    for (const key of ['cpu', 'machine', 'mac'] as const) {
      if (identifiers[key]) parts.push(identifiers[key]);
    }
    if (identifiers['os']) parts.push(identifiers['os']);
    return parts.join('|');
  }
}

// ---------------------------------------------------------------------------
// CacheManager — TTL-aware, atomic writes
// ---------------------------------------------------------------------------
export class CacheManager {
  private _cacheDir: string;
  private _cacheFile: string;
  private _tmpFile: string;
  private _corruptFile: string;
  private _ttlDays: number;
  private _cache: Record<string, any> | null = null;

  constructor(config: Record<string, any>, productId?: string) {
    const pid = productId || config?.product?.id || PRODUCT_ID;
    const safeName = pid.replace(/[^a-zA-Z0-9_-]/g, '_');
    const homeDir = process.env.WEBSMITH_TEMP_DIR || process.env.TMPDIR || process.env.TEMP || os.homedir();
    this._cacheDir = path.join(homeDir, '.websmith', safeName);
    this._cacheFile = path.join(this._cacheDir, 'cache.json');
    this._tmpFile = path.join(this._cacheDir, 'cache.tmp');
    this._corruptFile = path.join(this._cacheDir, 'cache.corrupt');
    this._ttlDays = config?.offline?.cache_days || config?.license?.offline_days || ${offlineDays};
  }

  private _ensureCacheDir(): void {
    fs.mkdirSync(this._cacheDir, { recursive: true });
  }

  private _loadCache(): Record<string, any> {
    if (this._cache !== null) return this._cache;
    this._ensureCacheDir();
    try {
      if (fs.existsSync(this._cacheFile)) {
        this._cache = JSON.parse(fs.readFileSync(this._cacheFile, 'utf-8'));
        return this._cache!;
      }
    } catch {
      this._preserveCorruptCache();
    }
    this._cache = {};
    return this._cache;
  }

  private _preserveCorruptCache(): void {
    try {
      if (fs.existsSync(this._cacheFile)) {
        if (fs.existsSync(this._corruptFile)) fs.unlinkSync(this._corruptFile);
        fs.renameSync(this._cacheFile, this._corruptFile);
      }
    } catch {
      try { fs.unlinkSync(this._cacheFile); } catch { /* ignore */ }
    }
  }

  private _saveCache(): void {
    if (this._cache === null) return;
    this._ensureCacheDir();
    try {
      fs.writeFileSync(this._tmpFile, JSON.stringify(this._cache, null, 2), 'utf-8');
      fs.renameSync(this._tmpFile, this._cacheFile);
    } catch {
      try { if (fs.existsSync(this._tmpFile)) fs.unlinkSync(this._tmpFile); } catch { /* ignore */ }
    }
  }

  get(key: string): any {
    const cache = this._loadCache();
    const entry = cache[key] as CacheEntry | undefined;
    if (!entry) return null;
    if (this._isExpired(entry)) {
      this.delete(key);
      return null;
    }
    return entry.value;
  }

  set(key: string, value: any): void {
    const cache = this._loadCache();
    cache[key] = { value, cached_at: Date.now() };
    this._saveCache();
  }

  delete(key: string): void {
    const cache = this._loadCache();
    if (key in cache) {
      delete cache[key];
      this._saveCache();
    }
  }

  clear(): void {
    this._cache = {};
    this._saveCache();
  }

  private _isExpired(entry: CacheEntry): boolean {
    const ttlMs = this._ttlDays * 24 * 60 * 60 * 1000;
    return (Date.now() - entry.cached_at) > ttlMs;
  }

  exists(): boolean {
    return fs.existsSync(this._cacheFile);
  }

  isCacheValid(): boolean {
    const cache = this._loadCache();
    const entry = cache['license_status'] as CacheEntry | undefined;
    if (!entry) return false;
    return !this._isExpired(entry);
  }

  isHardwareConsistent(currentHardwareId: string): boolean {
    const status = this.getLicenseStatus();
    if (!status) return true;
    if (!status.hardware_id) return true;
    return status.hardware_id === currentHardwareId;
  }

  invalidateIfHardwareMismatch(currentHardwareId: string): void {
    if (!this.isHardwareConsistent(currentHardwareId)) {
      this.invalidateLicenseStatus();
    }
  }

  getLicenseStatus(): Record<string, any> | null {
    return this.get('license_status');
  }

  setLicenseStatus(status: Record<string, any>): void {
    this.set('license_status', status);
  }

  invalidateLicenseStatus(): void {
    this.delete('license_status');
  }

  getLicenseKey(): string | null {
    const status = this.get('license_status');
    return status?.license_key || null;
  }

  markHasEverActivatedPaidLicense(): void {
    this.set('has_ever_activated_paid_license', true);
  }

  hasEverActivatedPaidLicense(): boolean {
    return this.get('has_ever_activated_paid_license') === true;
  }

  setOnboardingComplete(): void {
    this.set('onboarding_complete', true);
  }

  isOnboardingComplete(): boolean {
    return this.get('onboarding_complete') === true;
  }

  // ====================================================================
  // Message Queue (Offline Retry)
  // ====================================================================

  queueMessage(msg: Record<string, any>): void {
    const queue = this.getMessageQueue();
    msg.id = msg.id || \`q_\${Date.now()}_\${Math.random().toString(36).slice(2, 8)}\`;
    msg.status = msg.status || 'pending';
    msg.retry_count = msg.retry_count || 0;
    msg.max_retries = msg.max_retries || 5;
    msg.created_at = msg.created_at || Math.floor(Date.now() / 1000);
    msg.next_retry_at = msg.next_retry_at || Math.floor(Date.now() / 1000) + 60;
    queue.push(msg);
    this.set('message_queue', queue);
  }

  getMessageQueue(): Record<string, any>[] {
    return this.get('message_queue') || [];
  }

  saveMessageQueue(queue: Record<string, any>[]): void {
    this.set('message_queue', queue);
  }

  cleanupSentMessages(): void {
    const queue = this.getMessageQueue().filter(m => m.status !== 'sent');
    this.saveMessageQueue(queue);
  }

  getPendingCount(): number {
    return this.getMessageQueue().filter(m => m.status === 'pending' || m.status === 'failed').length;
  }
}

// ---------------------------------------------------------------------------
// ApiClient — HMAC-signed requests with retry
// ---------------------------------------------------------------------------
export class ApiClient {
  private config: Record<string, any>;
  private apiConfig: Record<string, any>;
  private baseUrl: string;
  private apiVersion: string;
  private apiKey: string;
  private apiSecret: string;
  private timeout: number;
  private retryCount: number;
  private productId: string;
  private hardware: HardwareDetector;
  private cache: CacheManager | null;

  constructor(
    config: Record<string, any>,
    hardware?: HardwareDetector,
    cache?: CacheManager | null
  ) {
    this.config = config;
    this.apiConfig = config.api || {};
    this.baseUrl = (this.apiConfig.url || API_URL).replace(/\\/+$/, '');
    this.apiVersion = this.apiConfig.version || 'v1';
    this.apiKey = this.apiConfig.public_key || '';
    this.apiSecret = this.apiConfig.secret || '';
    this.timeout = (this.apiConfig.timeout || 30000) / 1000;
    this.retryCount = this.apiConfig.retry_count || 3;
    this.productId = config.product?.id || PRODUCT_ID;
    this.hardware = hardware || new HardwareDetector();
    this.cache = cache || null;
  }

  private _getHardwareId(): string {
    return this.hardware.getFingerprint();
  }

  private _buildSignedHeaders(
    payload: Record<string, any>,
    method: string = 'POST',
    path: string = '',
    query: string = ''
  ): Record<string, string> {
    const timestamp = generateTimestamp();
    const nonce = generateNonce();
    const signature = signRequest(payload, this.apiSecret, timestamp, nonce, method, path, query);
    return {
      'Content-Type': 'application/json',
      'x-api-key': this.apiKey,
      'x-timestamp': timestamp,
      'x-nonce': nonce,
      'x-signature': signature,
    };
  }

  private async _request(
    endpoint: string,
    payload: Record<string, any>,
    retries?: number
  ): Promise<Record<string, any>> {
    const url = \`\${this.baseUrl}/api/\${this.apiVersion}/\${endpoint}\`;
    const maxRetries = retries ?? this.retryCount;
    const requestPayload = { ...payload };
    if (this.productId) {
      requestPayload.product_id = requestPayload.product_id || this.productId;
    }

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      const apiPath = \`/api/\${this.apiVersion}/\${endpoint}\`;
      const headers = this._buildSignedHeaders(requestPayload, 'POST', apiPath, '');

      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), this.timeout * 1000);

        const response = await fetch(url, {
          method: 'POST',
          headers,
          body: JSON.stringify(requestPayload),
          signal: controller.signal,
        });
        clearTimeout(timeoutId);

        let data: Record<string, any> = {};
        try {
          data = await response.json();
        } catch {
          const text = await response.text().catch(() => '');
          if (text) data = { message: text };
        }

        if (response.ok) return data;

        if (response.status === 429) {
          if (attempt < maxRetries) {
            const retryAfter = parseInt(response.headers.get('Retry-After') || '5', 10);
            await new Promise(resolve => setTimeout(resolve, retryAfter * 1000));
            continue;
          }
          throw new ApiError(429, 'Rate limit exceeded', data);
        }

        if (RETRYABLE_STATUSES.has(response.status)) {
          if (attempt < maxRetries) {
            await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 2000));
            continue;
          }
          throw new ApiError(response.status, 'Server error', data);
        }

        const message = data.message || data.error || \`HTTP \${response.status}\`;
        throw new ApiError(response.status, message, data);
      } catch (err: any) {
        if (err instanceof ApiError) throw err;
        if (err.name === 'AbortError') {
          if (attempt < maxRetries) {
            await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 2000));
            continue;
          }
          throw new ApiError(504, \`Request timeout after \${this.timeout}s\`);
        }
        if (err.type === 'system' || err.code === 'ECONNREFUSED' || err.code === 'ENOTFOUND') {
          if (attempt < maxRetries) {
            await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 2000));
            continue;
          }
          throw new ApiError(503, \`Connection error: \${err.message}\`);
        }
        if (attempt < maxRetries) {
          await new Promise(resolve => setTimeout(resolve, (attempt + 1) * 2000));
          continue;
        }
        throw new ApiError(500, \`Request failed: \${err.message}\`);
      }
    }
    throw new ApiError(500, \`Failed after \${maxRetries} retries\`);
  }

  private async _getRequest(
    endpoint: string,
    params?: Record<string, string>
  ): Promise<Record<string, any>> {
    const url = new URL(\`\${this.baseUrl}/api/\${this.apiVersion}/\${endpoint}\`);
    if (params) {
      for (const [key, value] of Object.entries(params)) {
        url.searchParams.set(key, value);
      }
    }
    try {
      const response = await fetch(url.toString(), {
        method: 'GET',
        headers: { 'Content-Type': 'application/json', 'x-api-key': this.apiKey },
        signal: AbortSignal.timeout(this.timeout * 1000),
      });
      let data: Record<string, any> = {};
      try { data = await response.json(); } catch { /* ignore */ }
      if (response.ok) return data;
      throw new ApiError(response.status, data.error?.message || \`HTTP \${response.status}\`, data);
    } catch (err: any) {
      if (err instanceof ApiError) throw err;
      throw new ApiError(500, \`Request failed: \${err.message}\`);
    }
  }

  async sendOtp(email: string): Promise<Record<string, any>> {
    return this._request('auth/otp/send', {
      email,
      product_id: this.productId,
      hardware_id: this._getHardwareId(),
    });
  }

  async verifyOtp(email: string, otp: string): Promise<Record<string, any>> {
    return this._request('auth/otp/verify', {
      email,
      otp,
      product_id: this.productId,
      hardware_id: this._getHardwareId(),
    });
  }

  async validateLicense(licenseKey: string, hardwareId?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const payload = { action: 'validate', license_key: licenseKey, hardware_id: hardwareId };
    const response = await this._request('license', payload);
    return response;
  }

  async activateLicense(licenseKey: string, hardwareId?: string, deviceName?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const payload: Record<string, any> = { action: 'activate', license_key: licenseKey, hardware_id: hardwareId };
    if (deviceName) payload.device_name = deviceName;
    const response = await this._request('license', payload);
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }

  async deactivateLicense(licenseKey: string, hardwareId?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const response = await this._request('license', { action: 'deactivate', license_key: licenseKey, hardware_id: hardwareId });
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }

  async renewLicense(licenseKey: string, extraDays?: number): Promise<Record<string, any>> {
    const payload: Record<string, any> = { action: 'renew', license_key: licenseKey };
    if (extraDays !== undefined) payload.extra_days = extraDays;
    const response = await this._request('license', payload);
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }

  async startTrial(email: string, customerName: string = '', customerData?: Record<string, any>): Promise<Record<string, any>> {
    const hardwareId = this._getHardwareId();
    const payload: Record<string, any> = { action: 'start', customer_email: email, customer_name: customerName, hardware_id: hardwareId };
    if (customerData) payload.customer_data = customerData;
    return this._request('trial', payload);
  }

  async getTrialStatus(hardwareId?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    return this._request('trial', { action: 'status', hardware_id: hardwareId });
  }

  async convertTrial(hardwareId?: string, plan?: string, name?: string, email?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const payload: Record<string, any> = { action: 'convert', hardware_id: hardwareId };
    if (plan) payload.plan = plan;
    if (name) payload.customer_name = name;
    if (email) payload.customer_email = email;
    const response = await this._request('trial', payload);
    if (this.cache) this.cache.invalidateLicenseStatus();
    return response;
  }

  async bindDevice(licenseKey: string, hardwareId?: string, deviceName?: string): Promise<Record<string, any>> {
    if (!hardwareId) hardwareId = this._getHardwareId();
    const payload: Record<string, any> = { action: 'bind', license_key: licenseKey, hardware_id: hardwareId };
    if (deviceName) payload.device_name = deviceName;
    return this._request('device', payload);
  }

  async verifyLicenseForRenewal(licenseKey: string): Promise<Record<string, any>> {
    return this._request('license/verify-renewal', { license_key: licenseKey });
  }

  async getAvailablePlans(licenseKey: string): Promise<Record<string, any>> {
    return this._request('license/available-plans', { license_key: licenseKey });
  }

  async sendRenewalRequest(data: {
    license_key: string;
    request_type: 'renew' | 'new';
    customer_name?: string;
    customer_email?: string;
    customer_mobile?: string;
    message?: string;
    current_plan_id?: string;
    current_plan_name?: string;
    requested_plan_id?: string;
    requested_plan_name?: string;
  }): Promise<Record<string, any>> {
    return this._request('license/send-renewal-request', data);
  }

  async sendReactivationRequest(data: {
    license_key: string;
    customer_name?: string;
    customer_email?: string;
    hardware_id?: string;
    message?: string;
  }): Promise<Record<string, any>> {
    if (!data.hardware_id) data.hardware_id = this._getHardwareId();
    return this._request('reactivations', data);
  }

  async sendSupportRequest(data: {
    license_key?: string;
    customer_name?: string;
    customer_email?: string;
    subject?: string;
    message: string;
  }): Promise<Record<string, any>> {
    return this._request('support', { ...data, request_type: 'SUPPORT' });
  }

  async getCountries(): Promise<Record<string, any>> {
    return this._getRequest('countries');
  }

  async getRequestHistory(email: string): Promise<Record<string, any>> {
    return this._getRequest('request', { email });
  }

  async sendOtp(email: string): Promise<Record<string, any>> {
    return this._request('auth/otp/send', { email, product_id: this.productId });
  }

  async verifyOtp(email: string, otp: string): Promise<Record<string, any>> {
    return this._request('auth/otp/verify', { email, otp, product_id: this.productId });
  }

  async registerCustomer(data: {
    name: string;
    email: string;
    mobile: string;
    country_code: string;
    hardware_id: string;
    company_name?: string;
  }): Promise<Record<string, any>> {
    return this._request('customer/register', { ...data, product_id: this.productId });
  }

  // ====================================================================
  // Universal Communication Engine
  // ====================================================================

  async createCommunication(params: Record<string, any>): Promise<Record<string, any>> {
    return this._request('communication/create', {
      category: params.category,
      customer_email: params.customer_email,
      customer_name: params.customer_name,
      subject: params.subject || '',
      message: params.message,
      product_id: params.product_id || this.productId,
      license_key: params.license_key || '',
      hardware_id: params.hardware_id || this._getHardwareId(),
      sdk_version: params.sdk_version || SDK_VERSION,
      runtime_type: params.runtime_type || RUNTIME_TYPE,
    });
  }

  async getConversation(conversationId: string): Promise<Record<string, any>> {
    return this._request(\`communication/\${conversationId}\`, {
      hardware_id: this._getHardwareId(),
    });
  }

  async replyToConversation(conversationId: string, message: string, customerName?: string, customerEmail?: string): Promise<Record<string, any>> {
    const payload: Record<string, any> = { message };
    if (customerName) payload.customer_name = customerName;
    if (customerEmail) payload.customer_email = customerEmail;
    payload.hardware_id = this._getHardwareId();
    return this._request(\`communication/\${conversationId}/reply\`, payload);
  }

  async listConversations(email: string): Promise<Record<string, any>> {
    return this._request('communication/list', {
      customer_email: email,
      hardware_id: this._getHardwareId(),
    });
  }

  async uploadAttachment(conversationId: string, filePath: string, fileContent?: string): Promise<Record<string, any>> {
    return this._request(\`communication/\${conversationId}/attach\`, {
      file_path: filePath,
      file_content: fileContent || '',
      hardware_id: this._getHardwareId(),
    });
  }

  // ====================================================================
  // Notifications
  // ====================================================================

  async getNotifications(email: string): Promise<Record<string, any>> {
    return this._request('notifications', {
      customer_email: email,
      hardware_id: this._getHardwareId(),
    });
  }

  async markNotificationRead(notificationId: string): Promise<Record<string, any>> {
    return this._request('notifications/read', {
      notification_id: notificationId,
      hardware_id: this._getHardwareId(),
    });
  }

  async getUnreadNotificationCount(email: string): Promise<Record<string, any>> {
    return this._request('notifications/unread-count', {
      customer_email: email,
      hardware_id: this._getHardwareId(),
    });
  }
}

// ---------------------------------------------------------------------------
// LicenseEngine — full lifecycle management
// ---------------------------------------------------------------------------
export class LicenseEngine {
  private config: Record<string, any>;
  private hardware: HardwareDetector;
  private cache: CacheManager;
  private client: ApiClient;
  private _status: LicenseStatusData | null = null;
  private _licenseKey: string | null = null;
  onLicenseReady: ((valid: boolean) => void) | null = null;

  constructor(config?: Record<string, any>) {
    this.config = config || loadConfig();
    this.hardware = new HardwareDetector();
    this.cache = new CacheManager(this.config);
    this.client = new ApiClient(this.config, this.hardware, this.cache);
    this._licenseKey = this.cache.getLicenseKey();
  }

  private _notifyReady(valid: boolean): void {
    if (this.onLicenseReady) {
      try { this.onLicenseReady(valid); } catch { }
    }
  }

  private _isValidStatus(status: LicenseStatusData | null): boolean {
    if (!status) return false;
    return status.status === 'active' || status.status === 'trial';
  }

  getClient(): ApiClient { return this.client; }
  getHardware(): HardwareDetector { return this.hardware; }
  getCache(): CacheManager { return this.cache; }
  getStatus(): LicenseStatusData | null { return this._status; }
  getLicenseKey(): string | null { return this._licenseKey; }
  hasLicenseKey(): boolean { return this._licenseKey !== null; }

  async initialize(): Promise<LicenseStatusData> {
    const hardwareId = this.hardware.getFingerprint();
    this.cache.invalidateIfHardwareMismatch(hardwareId);
    await this._processMessageQueue();
    if (this.cache.isCacheValid()) {
      const cached = this.cache.getLicenseStatus();
      if (cached) {
        this._status = LicenseEngine._toStatusData(cached);
        this._notifyReady(this._isValidStatus(this._status));
        return this._status;
      }
    }
    try {
      if (this._licenseKey) {
        try {
          const response = await this.client.validateLicense(this._licenseKey, hardwareId);
          const data = response.data || response;
          if (data.valid) {
            const statusStr = data.status || 'active';
            if (statusStr === 'expired') {
              this._status = {
                valid: false, status: 'expired',
                expires_at: data.expiry_date, days_remaining: 0,
                plan: data.plan, hardware_id: hardwareId,
                license_key: this._licenseKey, message: 'License has expired. Please renew.',
              };
              this._notifyReady(false);
              return this._status;
            }
            this._status = {
              valid: true, status: statusStr,
              expires_at: data.expiry_date,
              days_remaining: data.days_left ?? data.days_remaining ?? 0,
              plan: data.plan, hardware_id: hardwareId,
              license_key: this._licenseKey, message: 'License active',
            };
            this.cache.setLicenseStatus(this._status);
            this.cache.markHasEverActivatedPaidLicense();
            this._notifyReady(true);
            return this._status;
          } else {
            const serverStatus = data.status || '';
            if (serverStatus === 'expired') {
              this._status = {
                valid: false, status: 'expired',
                expires_at: data.expiry_date, days_remaining: 0,
                plan: data.plan, hardware_id: hardwareId,
                license_key: this._licenseKey, message: 'License has expired. Please renew.',
              };
              this._notifyReady(false);
              return this._status;
            }
            if (this.cache.hasEverActivatedPaidLicense()) {
              this._status = {
                valid: false, status: 'force_reactivation',
                hardware_id: hardwareId, license_key: this._licenseKey,
                message: 'License inactive. Please reactivate.',
              };
              this._notifyReady(false);
              return this._status;
            }
            this._status = {
              valid: false, status: 'force_activation',
              hardware_id: hardwareId, license_key: this._licenseKey,
              message: 'License key invalid. Please activate.',
            };
            this._notifyReady(false);
            return this._status;
          }
        } catch {
          if (this.cache.hasEverActivatedPaidLicense()) {
            this._status = {
              valid: false, status: 'force_reactivation',
              hardware_id: hardwareId, license_key: this._licenseKey,
              message: 'License validation failed. Please reactivate.',
            };
            this._notifyReady(false);
            return this._status;
          }
          this._status = {
            valid: false, status: 'force_activation',
            hardware_id: hardwareId, license_key: this._licenseKey,
            message: 'License validation failed. Please activate.',
          };
          this._notifyReady(false);
          return this._status;
        }
      } else {
        if (this.cache.hasEverActivatedPaidLicense()) {
          this._status = {
            valid: false, status: 'force_reactivation',
            hardware_id: hardwareId,
            message: 'License key missing. Please reactivate.',
          };
          this._notifyReady(false);
          return this._status;
        }
      }
      if (!this.cache.hasEverActivatedPaidLicense()) {
        const trialResponse = await this.client.getTrialStatus(hardwareId);
        const trialData = trialResponse.data || {};
        if (trialData.has_trial) {
          const statusStr = trialData.status || 'trial';
          if (statusStr === 'expired') {
            this._status = {
              valid: false, status: 'expired',
              expires_at: trialData.expiry_date, days_remaining: 0,
              plan: trialData.plan, hardware_id: hardwareId,
              message: 'Trial has expired. Please renew.',
            };
            this._notifyReady(false);
            return this._status;
          }
          this._status = {
            valid: statusStr === 'active', status: statusStr,
            expires_at: trialData.expiry_date,
            days_remaining: trialData.days_left ?? trialData.days_remaining ?? 0,
            plan: trialData.plan, hardware_id: hardwareId,
            message: \`Trial is \${statusStr}\`,
          };
          if (this._status.valid) {
            this.cache.setLicenseStatus(this._status);
          }
          this._notifyReady(this._isValidStatus(this._status));
          return this._status;
        }
      }
      if (this.cache.isOnboardingComplete()) {
        this._status = {
          valid: false, status: 'force_activation',
          hardware_id: hardwareId,
          message: 'No active license found. Please activate.',
        };
      } else {
        this._status = {
          valid: false, status: 'unlicensed',
          hardware_id: hardwareId,
          message: 'No license or trial found',
        };
      }
      this._notifyReady(false);
      return this._status;
    } catch (err: any) {
      const cached = this.cache.getLicenseStatus();
      if (cached) {
        this._status = LicenseEngine._toStatusData(cached);
        this._notifyReady(this._isValidStatus(this._status));
        return this._status;
      }
      this._status = {
        valid: false, status: 'error',
        message: \`Unexpected error: \${err.message || err}\`,
      };
      this._notifyReady(false);
      return this._status;
    }
  }

  async validate(key?: string): Promise<LicenseResult> {
    const hardwareId = this.hardware.getFingerprint();
    try {
      const result = await this.client.validateLicense(key || '', hardwareId);
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async activate(key: string, deviceName?: string): Promise<LicenseResult> {
    try {
      const hardwareId = this.hardware.getFingerprint();
      const result = await this.client.activateLicense(key, hardwareId, deviceName || '');
      if (result.success || result.valid) {
        this._licenseKey = key;
        await this.initialize();
        this.cache.markHasEverActivatedPaidLicense();
      }
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async deactivate(key?: string): Promise<LicenseResult> {
    const licenseKey = key || this._licenseKey;
    if (!licenseKey) return { success: false, status: 'error', message: 'License key unavailable. Provide a key.' };
    try {
      const result = await this.client.deactivateLicense(licenseKey);
      if (result.success) {
        this.cache.invalidateLicenseStatus();
        this._status = null;
        if (!key) this._licenseKey = null;
      }
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async renew(key?: string, extraDays?: number): Promise<LicenseResult> {
    const licenseKey = key || this._licenseKey;
    if (!licenseKey) return { success: false, status: 'error', message: 'License key unavailable. Activate first.' };
    try {
      const result = await this.client.renewLicense(licenseKey, extraDays);
      if (result.success) await this.initialize();
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async startTrial(email: string, name?: string): Promise<LicenseResult> {
    try {
      const result = await this.client.startTrial(email, name || '');
      if (result.success) await this.initialize();
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async checkTrial(hardwareId?: string): Promise<LicenseResult> {
    try {
      return await this.client.getTrialStatus(hardwareId);
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async convertTrial(hardwareId: string, plan: string, name: string, email: string): Promise<LicenseResult> {
    try {
      const result = await this.client.convertTrial(hardwareId, plan, name, email);
      if (result.success) {
        if (result.license_key) this._licenseKey = result.license_key;
        await this.initialize();
        this.cache.markHasEverActivatedPaidLicense();
      }
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async viewHardwareStatus(): Promise<LicenseResult> {
    try {
      const status: Record<string, any> = { current_hardware_id: this._hardware.getFingerprint() };
      const cached = this._cache.getLicenseStatus();
      if (cached?.hardware_id) {
        status.registered_hardware_id = cached.hardware_id;
        status.matched = status.current_hardware_id === cached.hardware_id;
      }
      status.message = 'Hardware replacement requires administrator approval. Please contact support.';
      return { success: true, status: 'ok', data: status };
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async bindDevice(licenseKey: string, deviceName?: string): Promise<LicenseResult> {
    try {
      const result = await this.client.bindDevice(licenseKey, undefined, deviceName);
      if (result.success) await this.initialize();
      return result;
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async verifyLicenseForRenewal(licenseKey?: string): Promise<LicenseResult> {
    const key = licenseKey || this._licenseKey;
    if (!key) return { success: false, status: 'error', message: 'License key unavailable.' };
    try {
      return await this.client.verifyLicenseForRenewal(key);
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async getAvailablePlans(licenseKey?: string): Promise<LicenseResult> {
    const key = licenseKey || this._licenseKey;
    if (!key) return { success: false, status: 'error', message: 'License key unavailable.' };
    try {
      return await this.client.getAvailablePlans(key);
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async sendRenewalRequest(data: {
    license_key: string;
    request_type: 'renew' | 'new';
    customer_name?: string;
    customer_email?: string;
    customer_mobile?: string;
    message?: string;
    current_plan_id?: string;
    current_plan_name?: string;
    requested_plan_id?: string;
    requested_plan_name?: string;
  }): Promise<LicenseResult> {
    try {
      return await this.client.sendRenewalRequest(data);
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async sendReactivationRequest(data: {
    license_key: string;
    customer_name?: string;
    customer_email?: string;
    message?: string;
  }): Promise<LicenseResult> {
    try {
      return await this.client.sendReactivationRequest(data);
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async sendSupportRequest(data: {
    license_key?: string;
    customer_name?: string;
    customer_email?: string;
    subject?: string;
    message: string;
  }): Promise<LicenseResult> {
    try {
      return await this.client.sendSupportRequest(data);
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async getCountries(): Promise<LicenseResult> {
    try {
      return await this.client.getCountries();
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  async getRequestHistory(email: string): Promise<LicenseResult> {
    try {
      return await this.client.getRequestHistory(email);
    } catch (err: any) {
      return { success: false, status: 'error', message: err.message || String(err) };
    }
  }

  isValid(): boolean {
    if (!this._status) return false;
    return this._status.status === 'active' || this._status.status === 'trial';
  }

  getLicenseInfo(): LicenseStatusData | null {
    return this._status;
  }

  private static _toStatusData(data: any): LicenseStatusData {
    return {
      valid: !!data.valid,
      status: data.status || 'unknown',
      expires_at: data.expires_at,
      days_remaining: data.days_remaining ?? 0,
      plan: data.plan,
      hardware_id: data.hardware_id,
      message: data.message,
    };
  }

  // ====================================================================
  // Message Queue Processing
  // ====================================================================

  private async _processMessageQueue(): Promise<void> {
    const queue = this.cache.getMessageQueue();
    let changed = false;
    for (const msg of queue) {
      if (msg.status === 'sent') continue;
      const now = Math.floor(Date.now() / 1000);
      if (now < (msg.next_retry_at || 0)) continue;
      if (msg.retry_count >= msg.max_retries) continue;
      msg.status = 'sending';
      try {
        await this.client.createCommunication(msg);
        msg.status = 'sent';
        changed = true;
      } catch (e: any) {
        msg.retry_count = (msg.retry_count || 0) + 1;
        msg.last_error = e.message || String(e);
        const expBackoff = Math.pow(2, msg.retry_count) * 60;
        msg.next_retry_at = now + expBackoff;
        msg.status = 'failed';
        changed = true;
      }
    }
    if (changed) {
      this.cache.saveMessageQueue(queue);
      this.cache.cleanupSentMessages();
    }
  }

  // ====================================================================
  // Universal Communication Engine
  // ====================================================================

  async createCommunication(params: Record<string, any>): Promise<Record<string, any>> {
    try {
      return await this.client.createCommunication(params);
    } catch (e: any) {
      this.cache.queueMessage(params);
      return { success: false, message: 'Message queued for delivery when online.', queued: true };
    }
  }

  async getConversation(conversationId: string): Promise<Record<string, any>> {
    return this.client.getConversation(conversationId);
  }

  async replyToConversation(conversationId: string, message: string, customerName?: string, customerEmail?: string): Promise<Record<string, any>> {
    try {
      return await this.client.replyToConversation(conversationId, message, customerName, customerEmail);
    } catch (e: any) {
      const cached = this.cache.getLicenseStatus();
      this.cache.queueMessage({
        category: 'general',
        customer_email: customerEmail || cached?.customer_email || '',
        customer_name: customerName || cached?.customer_name || '',
        subject: \`Reply to conversation \${conversationId}\`,
        message,
      });
      return { success: false, message: 'Reply queued for delivery when online.', queued: true };
    }
  }

  async listConversations(email: string): Promise<Record<string, any>> {
    return this.client.listConversations(email);
  }

  async getNotifications(email: string): Promise<Record<string, any>> {
    return this.client.getNotifications(email);
  }

  async markNotificationRead(notificationId: string): Promise<Record<string, any>> {
    return this.client.markNotificationRead(notificationId);
  }

  async getUnreadNotificationCount(email: string): Promise<Record<string, any>> {
    return this.client.getUnreadNotificationCount(email);
  }
}

`,
    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "declaration": true,
    "outDir": "./dist",
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["*.ts"]
}
`,
    'package.json': `{
  "name": "${pkgName}",
  "version": "${context.kitVersion}",
  "description": "${context.productName} SDK — license management client for ${context.runtime}",
  "main": "dist/client.js",
  "types": "dist/client.d.ts",
  "files": [
    "dist/",
    "config/"
  ],
  "scripts": {
    "build": "tsc",
    "prepublishOnly": "npm run build"
  },
  "license": "MIT",
  "dependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  }
}
`,
    'README.md': `# ${context.productName} SDK (TypeScript)

## Version
${context.kitVersion}

## Installation

\`\`\`bash
npm install ${pkgName}
\`\`\`

Or copy the generated \`client.ts\` into your project directly.

## Quick Start

\`\`\`typescript
import { LicenseEngine } from './client';

async function main() {
  const engine = new LicenseEngine();
  const status = await engine.initialize();
  console.log('License status:', status);
}

main();
\`\`\`

## Lifecycle Guide

### 1. Initialize

Loads config from \`./config/api-config.json\` and checks cached license status.

\`\`\`typescript
const engine = new LicenseEngine();
const status = await engine.initialize();
console.log(status.valid ? 'Licensed' : 'Unlicensed');
\`\`\`

### 2. Validate a License Key

\`\`\`typescript
const result = await engine.validate('XXXX-XXXX-XXXX-XXXX');
console.log('Valid:', engine.isValid());
\`\`\`

### 3. Activate a License

Binds the license to the current hardware fingerprint.

\`\`\`typescript
const result = await engine.activate('XXXX-XXXX-XXXX-XXXX', 'My Machine');
if (result.success) console.log('Activated');
\`\`\`

### 4. Start a Trial

\`\`\`typescript
const result = await engine.startTrial('user@example.com', 'John Doe');
if (result.success) console.log('Trial started');
\`\`\`

### 5. Check Trial Status

\`\`\`typescript
const result = await engine.checkTrial();
console.log('Trial:', result.status);
\`\`\`

### 6. Convert Trial to Full License

\`\`\`typescript
const result = await engine.convertTrial(
  engine.getHardware().getFingerprint(),
  'premium',
  'John Doe',
  'user@example.com'
);
if (result.success) console.log('Converted to full license');
\`\`\`

### 7. Renew a License

\`\`\`typescript
const result = await engine.renew(undefined, 365);
if (result.success) console.log('License renewed');
\`\`\`

### 8. Bind Device

Associate a license with a specific device name.

\`\`\`typescript
const result = await engine.bindDevice('XXXX-XXXX-XXXX-XXXX', 'Workstation-1');
\`\`\`

### 10. Deactivate

\`\`\`typescript
const result = await engine.deactivate();
if (result.success) console.log('License deactivated');
\`\`\`

## API Endpoints

| Method | Endpoint | Description |
|--------|----------|-------------|
| POST | \`/api/v1/license\` | validate, activate, deactivate, renew |
| POST | \`/api/v1/trial\` | start, status, convert |
| POST | \`/api/v1/device\` | bind, replace |
| POST | \`/api/v1/auth/otp/*\` | send, verify |
| GET | \`/api/v1/countries\` | country list |
| GET | \`/api/v1/status\` | health check |

## Configuration

Place \`config/api-config.json\` in your project root:

\`\`\`json
{
  "api": {
    "url": "${apiUrl}",
    "public_key": "your-api-key",
    "secret": "your-api-secret",
    "version": "v1",
    "timeout": 30000,
    "retry_count": 3
  },
  "product": {
    "id": "${context.productId}",
    "name": "${context.productName}"
  }
}
\`\`\`

## License

Generated by Websmith License API Center
Copyright (c) ${new Date().getFullYear()}
`,

    // ================================================================
    // UNIVERSAL LICENSE CENTER & EMAIL DIALOG
    // ================================================================

    'universal_license_center.ts': `/**
 * ${context.productName} SDK - Universal License Center
 * Generated by Websmith License API Center | ${context.generatedAt}
 * Do not edit directly.
 */
import { LicenseEngine, LicenseStatus, ApiClient, HardwareDetector, CacheManager } from './client';

const SDK_VERSION = '${context.kitVersion}';
const RUNTIME_TYPE = '${context.runtime}';

export class UniversalLicenseCenter {
  private engine: LicenseEngine;
  private client: ApiClient;
  private hardware: HardwareDetector;
  private cache: CacheManager;
  private config: Record<string, any>;
  private branding: Record<string, string>;
  private status: any = null;
  private _locked: boolean = true;
  onLicenseReady: ((valid: boolean) => void) | null = null;

  constructor(config?: Record<string, any>, onLicenseReady?: ((valid: boolean) => void) | null) {
    this.config = config || {};
    this.branding = this._loadBranding();
    this.hardware = new HardwareDetector();
    this.cache = new CacheManager(this.config);
    this.engine = new LicenseEngine(this.config);
    this.client = new ApiClient(this.config, this.hardware, this.cache);
    if (onLicenseReady) {
      this.onLicenseReady = onLicenseReady;
      this.engine.onLicenseReady = (valid: boolean) => {
        this._locked = !valid;
        if (this.onLicenseReady) {
          try { this.onLicenseReady(valid); } catch { }
        }
      };
    }
  }

  private _loadBranding(): Record<string, string> {
    const b = this.config.branding || {};
    const p = this.config.product || {};
    return {
      company_name: b.company_name || '${companyName}',
      product_name: p.name || '${context.productName}',
      support_email: b.support_email || '',
      sales_email: b.sales_email || '',
      website_url: b.website_url || '',
      sender_name: b.sender_name || 'Support Team',
      welcome_text: b.welcome_text || 'Welcome!',
      license_text: b.license_text || 'License',
      tagline: b.tagline || 'License Management',
    };
  }

  private _isValidForUnlock(): boolean {
    if (!this.status) return false;
    return this.status.status === 'active' || this.status.status === 'trial';
  }

  async initialize(): Promise<any> {
    this.status = await this.engine.initialize();
    this._locked = !this._isValidForUnlock();
    return this.status;
  }

  async show(): Promise<Record<string, any>> {
    console.log('=== UNIVERSAL LICENSE CENTER ===');
    console.log(\`SDK Version: \${SDK_VERSION} | Runtime: \${RUNTIME_TYPE}\`);
    await this.initialize();
    const needsWelcome = this.status?.status === 'unlicensed' && !this.cache.isOnboardingComplete();
    return {
      status: this.status ? (this.status.toDict ? this.status.toDict() : this.status) : null,
      needs_welcome: needsWelcome,
      is_locked: this._locked,
    };
  }

  getStatus(): any { return this.status; }
  getLicenseKey(): string | null { return this.engine.getLicenseKey(); }
  getHardwareId(): string { return this.hardware.getFingerprint(); }
  isValid(): boolean { return !this._locked; }
  isLocked(): boolean { return this._locked; }

  async startTrial(name: string, email: string): Promise<Record<string, any>> {
    if (!name.trim() || !email.trim()) return { success: false, message: 'Name and email required.' };
    const result = await this.engine.startTrial(email.trim(), name.trim());
    if (result.success) {
      await this.initialize();
      this._locked = !this._isValidForUnlock();
    }
    return result;
  }

  async activateLicense(licenseKey: string): Promise<Record<string, any>> {
    if (!licenseKey.trim()) return { success: false, message: 'License key required.' };
    const result = await this.engine.activate(licenseKey.trim());
    if (result.success) {
      await this.initialize();
      this._locked = !this._isValidForUnlock();
    }
    return result;
  }

  async renew(extraDays?: number): Promise<Record<string, any>> {
    const result = await this.engine.renew(extraDays);
    if (result.success) {
      await this.initialize();
      this._locked = !this._isValidForUnlock();
    }
    return result;
  }

  async viewHardwareStatus(): Promise<Record<string, any>> {
    return this.engine.viewHardwareStatus();
  }

  async deactivate(licenseKey?: string): Promise<Record<string, any>> {
    const result = this.engine.deactivate(licenseKey);
    this._locked = true;
    return result;
  }
}
`,
    'universal_email_dialog.ts': `/**
 * ${context.productName} SDK - Universal Email Dialog (internal helper)
 * Generated by Websmith License API Center | ${context.generatedAt}
 * Do not edit directly.
 */
import { ApiClient, HardwareDetector, CacheManager } from './client';

const SDK_VERSION = '${context.kitVersion}';
const RUNTIME_TYPE = '${context.runtime}';

interface EmailDialogOptions {
  requestType: string;
  subject?: string;
  autoFill?: {
    customer_name?: string;
    customer_email?: string;
    product_name?: string;
    plan_name?: string;
    license_key?: string;
    hardware_id?: string;
  };
}

export class UniversalEmailDialog {
  private config: Record<string, any>;
  private client: ApiClient;
  private hardware: HardwareDetector;
  private cache: CacheManager;

  constructor(
    config: Record<string, any>,
    client: ApiClient,
    hardware: HardwareDetector,
    cache: CacheManager,
  ) {
    this.config = config;
    this.client = client;
    this.hardware = hardware;
    this.cache = cache;
  }

  async show(options: EmailDialogOptions): Promise<Record<string, any>> {
    const productName = options.autoFill?.product_name || this.config.product?.name || '${context.productName}';
    const supportEmail = this.config.branding?.support_email || 'support@example.com';
    const cached = this.cache.getLicenseStatus() || {};

    const name = options.autoFill?.customer_name || cached.customer_name || '';
    const email = options.autoFill?.customer_email || cached.customer_email || '';
    const hardwareId = options.autoFill?.hardware_id || this.hardware.getFingerprint() || '';
    const licenseKey = options.autoFill?.license_key || cached.license_key || '';
    const planName = options.autoFill?.plan_name || cached.plan || '';

    try {
      const payload: Record<string, any> = {
        request_type: options.requestType,
        customer_name: name || 'SDK User',
        customer_email: email || 'user@example.com',
        product_name: productName,
        plan_name: planName,
        license_key: licenseKey,
        hardware_id: hardwareId,
        sdk_version: SDK_VERSION,
        runtime_type: RUNTIME_TYPE,
        subject: options.subject || \`\${options.requestType} Request\`,
        message: '',
      };

      return await this.client.sendSupportRequest({
        license_key: licenseKey,
        customer_name: name,
        customer_email: email,
        subject: options.subject || \`\${options.requestType} Request\`,
        message: '',
      });
    } catch (e: any) {
      return { sent: false, error: e.message, fallback_email: supportEmail };
    }
  }
}
`,
    'index.ts': `/**
 * ${context.productName} SDK - Universal License Center
 * Generated by Websmith License API Center | ${context.generatedAt}
 * Do not edit directly.
 */
import { LicenseEngine, LicenseStatus, ApiClient, ApiError, HardwareDetector, CacheManager } from './client';
import { UniversalLicenseCenter } from './universal_license_center';

export { UniversalLicenseCenter, LicenseEngine, LicenseStatus, ApiClient, ApiError, HardwareDetector, CacheManager };
`,
  };
}
