graph TD
AboutPage --> PublicPage
AboutPage --> SimplePublicContent
AdminDashboardPage --> Card
AdminServicesPage --> Button
AdminServicesPage --> Card
AdminServicesPage --> ServiceModal
AdminServicesPage --> ViewModeToggle
AdminSoftwareStorePage --> NavbarVisibilityToggle
AdminsPage --> ConfirmationModal
AdminsPage --> ViewModeToggle
BlogPage --> PublicPage
BlogPage --> SimplePublicContent
CareersPage --> PublicPage
CareersPage --> SimplePublicContent
ClientDashboardPage --> Card
ClientInvoicesPage --> Modal
ClientLayout --> ForcedPasswordResetModal
ClientLayout --> LeadFunnelProvider
ClientLayout --> PublicFooter
ClientLayout --> PublicSiteNav
ClientLayout --> PublicThemeProvider
ClientLayout --> Sidebar
ClientTicketsPage --> Modal
ClientsPage --> ClientCard
ClientsPage --> ClientModal
ClientsPage --> ConfirmationModal
ClientsPage --> NavbarVisibilityToggle
ClientsPage --> ViewModeToggle
ContactPage --> PublicPage
ContactPage --> SimplePublicContent
DashboardPage --> Card
DeveloperDashboardPage --> Card
DeveloperNotificationsPage --> Card
DeveloperProjectsPage --> Card
DeveloperProjectsPage --> KanbanBoard
DeveloperTasksPage --> Card
DeveloperTasksPage --> KanbanBoard
DevelopersPage --> ConfirmationModal
DevelopersPage --> DeveloperCard
DevelopersPage --> DeveloperModal
DevelopersPage --> NavbarVisibilityToggle
DevelopersPage --> ViewModeToggle
DocumentationPage --> PublicPage
DocumentationPage --> SimplePublicContent
GlobalSearchBar --> SearchContext
IntegrationsPage --> Button
IntegrationsPage --> Card
IntegrationsPage --> SDKGenerationDialog
InternalApiLayout --> NotificationProvider
InternalApiLayout --> Sidebar
InternalApiLayout --> ThemeProvider
InternalApiLayout --> Topbar
InvoicesPage --> Modal
InvoicesPage --> ViewModeToggle
LandingPage --> LeadCapturePopup
LandingPage --> LeadFunnelProvider
LandingPage --> PublicFooter
LandingPage --> PublicSiteNav
LeadCapturePopup --> Button
LeadCapturePopup --> LeadFunnelProvider
LeadCapturePopup --> Modal
LeadFormClient --> Button
LeadFormClient --> Card
LeadFormClient --> Input
LeadFormClient --> LeadFunnelProvider
LeadFormPage --> LeadFormClient
LeadFunnelProvider --> LeadFunnelWizardModal
LeadFunnelWizardModal --> Button
LeadFunnelWizardModal --> LeadFormClient
LeadFunnelWizardModal --> LeadFunnelProvider
LeadFunnelWizardModal --> Modal
LeadFunnelWizardModal --> ServiceSelectionClient
LicenseCenterPage --> BulkOperationsTab
LicenseCenterPage --> GenerateLicenseTab
LicenseCenterPage --> HardwareSummaryTab
LicenseCenterPage --> LicenseManagerTab
LicenseCenterPage --> LogsSummaryTab
LicenseCenterPage --> RenewalsTab
LicenseCenterPage --> SearchContext
LicenseCenterPage --> TrialsTab
LicenseCenterPage --> ValidationCenterTab
LoginPage --> LeadFunnelProvider
LoginPage --> PublicSiteNav
MessagesPage --> ViewModeToggle
NotificationBell --> NotificationDropdown
NotificationDropdown --> NotificationItem
PUBLIC_SITE_NAV_ITEMS --> LeadFunnelProvider
PUBLIC_SITE_NAV_ITEMS --> PublicThemeProvider
PaymentsPage --> Modal
PaymentsPage --> ViewModeToggle
PrivacyPage --> PublicPage
PrivacyPage --> SimplePublicContent
ProjectsPage --> KanbanBoard
ProjectsPage --> NavbarVisibilityToggle
ProjectsPage --> ProjectCard
ProjectsPage --> ProjectModal
PublicSiteNav --> LeadFunnelProvider
PublicSiteNav --> PublicThemeProvider
RootLayout --> ClientLayout
SDKGenerationDialog --> CloseConfirmDialog
SDKGenerationDialog --> LiveLogs
SDKGenerationDialog --> PerformanceTable
SDKGenerationDialog --> ProgressBar
SDKGenerationDialog --> RetryInfo
SDKGenerationDialog --> StepTimeline
SDKGenerationDialog --> SuccessActions
SDKGenerationDialog --> TimelineView
ServiceSelectionClient --> Button
ServiceSelectionClient --> Card
ServiceSelectionClient --> LeadFunnelProvider
ServicesPage --> ServiceSelectionClient
SuccessPage --> Button
SuccessPage --> Card
SupportPage --> PublicPage
SupportPage --> SimplePublicContent
TasksPage --> KanbanBoard
TasksPage --> TaskCard
TasksPage --> TaskModal
TermsPage --> PublicPage
TermsPage --> SimplePublicContent
Topbar --> NotificationBell
Topbar --> ThemeSwitcher